
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./wsgi.py:/app/wsgi.py
      - ./app/static/css:/app/app/static/css
    command: >
      gunicorn --reload -w 1 -k gthread -b 0.0.0.0:8000 --timeout 120 wsgi:app
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    working_dir: /app
    command: >
      python app/worker.py
    restart: unless-stopped
    depends_on:
      - web