"""Add unique constraint to ledger_entries

Revision ID: e43c3cdd786d
Revises: acdf698aaca3
Create Date: 2025-10-01 16:20:33.940951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43c3cdd786d'
down_revision = 'acdf698aaca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ledger_reference', ['user_id', 'ref_type', 'ref_id'])

    with op.batch_alter_table('user_twitter_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_twitter_connections_twitter_user'))
        batch_op.create_index('ix_user_twitter_connections_twitter_user', ['twitter_user_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_twitter_connections_user'))
        batch_op.create_index('ix_user_twitter_connections_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_twitter_connections', schema=None) as batch_op:
        batch_op.drop_index('ix_user_twitter_connections_user')
        batch_op.create_index(batch_op.f('ix_user_twitter_connections_user'), ['user_id'], unique=True)
        batch_op.drop_index('ix_user_twitter_connections_twitter_user')
        batch_op.create_index(batch_op.f('ix_user_twitter_connections_twitter_user'), ['twitter_user_id'], unique=True)

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ledger_reference', type_='unique')

    # ### end Alembic commands ###
