"""indexes for follow SSE and fee payouts

Revision ID: e5302935e8ee
Revises: b4dcafee1234
Create Date: 2025-09-26 21:19:20.357413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5302935e8ee'
down_revision = 'b4dcafee1234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burn_events', schema=None) as batch_op:
        batch_op.create_index('ix_burn_events_created', ['created_at'], unique=False)
        batch_op.create_index('ix_burn_events_pool_created', ['pool_id', 'created_at'], unique=False)

    with op.batch_alter_table('creator_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_follows_creator'))
        batch_op.drop_index(batch_op.f('ix_creator_follows_follower'))

    with op.batch_alter_table('fee_distribution_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_rules_creator'))
        batch_op.drop_index(batch_op.f('ix_fee_rules_minter'))
        batch_op.drop_index(batch_op.f('ix_fee_rules_pool'))

    with op.batch_alter_table('fee_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_payouts_pool'))
        batch_op.create_index('ix_fee_payouts_pool_entity_asset_created', ['pool_id', 'entity', 'asset', 'created_at'], unique=False)

    with op.batch_alter_table('token_infos', schema=None) as batch_op:
        batch_op.create_index('ix_token_infos_launch_at', ['launch_at'], unique=False)
        batch_op.create_index('ix_token_infos_launch_user', ['launch_user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('token_infos', schema=None) as batch_op:
        batch_op.drop_index('ix_token_infos_launch_user')
        batch_op.drop_index('ix_token_infos_launch_at')

    with op.batch_alter_table('fee_payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_payouts_pool_entity_asset_created')
        batch_op.create_index(batch_op.f('ix_fee_payouts_pool'), ['pool_id'], unique=False)

    with op.batch_alter_table('fee_distribution_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_rules_pool'), ['pool_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fee_rules_minter'), ['minter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_rules_creator'), ['creator_user_id'], unique=False)

    with op.batch_alter_table('creator_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_follows_follower'), ['follower_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_follows_creator'), ['creator_user_id'], unique=False)

    with op.batch_alter_table('burn_events', schema=None) as batch_op:
        batch_op.drop_index('ix_burn_events_pool_created')
        batch_op.drop_index('ix_burn_events_created')

    # ### end Alembic commands ###
